apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: activitystreams
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: ./Manifest
    repoURL: ssh://APKA5H5MXV4HF5NLUPXL@git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/argocd-test
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
